name: rickandmorty
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  bloc: ^8.1.0
  bloc_test: ^9.1.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter_bloc: ^8.1.1
  lazy_load_scrollview: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true
